[2024-03-10T16:07:22.944+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=dag_carbon_intensity/run_id=manual__2024-03-10T16:06:05.835824+00:00/task_id=load_data permission to 509
[2024-03-10T16:07:22.997+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=dag_carbon_intensity/run_id=manual__2024-03-10T16:06:05.835824+00:00/task_id=load_data permission to 509
[2024-03-10T16:07:23.068+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_carbon_intensity.load_data manual__2024-03-10T16:06:05.835824+00:00 [queued]>
[2024-03-10T16:07:23.085+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_carbon_intensity.load_data manual__2024-03-10T16:06:05.835824+00:00 [queued]>
[2024-03-10T16:07:23.087+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 4
[2024-03-10T16:07:23.107+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data> on 2024-03-10 16:06:05.835824+00:00
[2024-03-10T16:07:23.115+0000] {standard_task_runner.py:57} INFO - Started process 4544 to run task
[2024-03-10T16:07:23.121+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_carbon_intensity', 'load_data', 'manual__2024-03-10T16:06:05.835824+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/dag_carbon_intensity.py', '--cfg-path', '/tmp/tmp6a_yoqtb']
[2024-03-10T16:07:23.124+0000] {standard_task_runner.py:85} INFO - Job 140: Subtask load_data
[2024-03-10T16:07:23.211+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=dag_carbon_intensity/run_id=manual__2024-03-10T16:06:05.835824+00:00/task_id=load_data permission to 509
[2024-03-10T16:07:23.223+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_carbon_intensity.load_data manual__2024-03-10T16:06:05.835824+00:00 [running]> on host b90b2ddba1ac
[2024-03-10T16:07:23.338+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_carbon_intensity' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-10T16:06:05.835824+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-10T16:06:05.835824+00:00'
[2024-03-10T16:07:23.343+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: load_carbon_intensity_data() missing 2 required positional arguments: 'start' and 'end'
[2024-03-10T16:07:23.366+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_carbon_intensity, task_id=load_data, execution_date=20240310T160605, start_date=20240310T160723, end_date=20240310T160723
[2024-03-10T16:07:23.392+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 140 for task load_data (load_carbon_intensity_data() missing 2 required positional arguments: 'start' and 'end'; 4544)
[2024-03-10T16:07:23.423+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-03-10T16:07:23.483+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
